# Generated by Django 5.2.7 on 2025-10-22 06:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stories', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='story',
            name='review_note',
            field=models.TextField(blank=True, null=True, verbose_name='审核备注'),
        ),
        migrations.AddField(
            model_name='story',
            name='status',
            field=models.CharField(choices=[('pending', '待审核'), ('approved', '已发布'), ('rejected', '已拒绝')], default='pending', max_length=10, verbose_name='审核状态'),
        ),
    ]
