# Generated by Django 5.2.7 on 2025-10-22 03:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customeruser',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='customeruser',
            name='is_staff',
            field=models.BooleanField(default=False),
        ),
    ]
